FACTION_GENERAL:
  STARTING_DTR: 1.1
  DTR_PER_PLAYER: 0.5
  REGEN_DELAY: 90 #every 90 seconds regen 0.1 dtr
  ALLIES:
    ENABLED: TRUE
    DAMAGE_ALLIES: FALSE
    MAX_ALLIES: 1
  MAX_PLAYERS: 30
FACTION_NAME:
  MAX_CHARACTERS: 16
  MIN_CHARACTERS: 3
  BLOCKED_NAMES:
    - "hcteams" # ;)
TAB_LIST:
  ENABLED: TRUE
  FRIENDLY_COLOR: "DARK_GREEN"
  ALLY_COLOR: "LIGHT_PURPLE"
  ENEMY_COLOR: "YELLOW"

FACTION_CHAT:
  ENABLED: TRUE
  NO_FACTION: ""
  FRIENDLY: "&6[&2%TAG%&6]&r"
  ALLY: "&6[&d%TAG%&6]&r"
  ENEMY: "&6[&e%TAG%&6]&r"